### ISSUE TITLE
On IE6 the simplemodal-wrap has no height and the contents inside collapse

### ISSUE THREAD

**Issue by codeuniquely** [ericmmartin/simplemodal#18]
Using version 1.4.3 release with a fairly simple calls
It works on all other IE versions and other browsers makes, just collapses on IE6

called using:

$('#popup-box').modal({
	opacity: 50,
	overlayId: 'popup-box-overlay',
	containerId: 'overlay-container',
	closeClass: 'modal-close'
});

**Comment by JohnSThomas** [comment]
IE6 is no longer supported.
