### ISSUE TITLE
ieQuirks detected on IE9

### ISSUE THREAD

**Issue by itzilev** [ericmmartin/simplemodal#22]
Hi, after updating from jQuery 1.6 to 1.8 this test :

ieQuirks = $.browser.msie && !$.support.boxModel; 

resolves randomly(different PCs same IE9) to true. According to jQuery change logs, boxModel feature is deprecated since v 1.7.1. For my use I bypass this by replacing 
 !$.support.boxModel with parseInt($.browser.version) < 8 but I'm not sure it's clean solution.

Regards
Ivan

**Comment by dsgh** [comment]
Fixed in 184a26a4861c80488eeb37e3510563ad5b394987

**Comment by JohnSThomas** [comment]
This was marked as fixed without further comment. Closing.
