### ISSUE TITLE
simplemodal bower.json's license is GPL?

### ISSUE THREAD

**Issue by iwdmb** [ericmmartin/simplemodal#62]
bower.json:

```
"license": "**GPL**",
```

I think it should be **GPL、MIT**

```
"license": [
  "MIT",
  "GPL"
]
```

Reference: [simplemodal/License.txt](https://github.com/ericmmartin/simplemodal/blob/master/License.txt)

**Comment by JohnSThomas** [comment]
Agreed.

**Comment by JohnSThomas** [comment]
Merged
