### ISSUE TITLE
Modal doesn't open when another modal is open

### ISSUE THREAD

**Issue by ismaelw** [ericmmartin/simplemodal#64]
I have a modal with two buttons in it. Both of these buttons should open another modal.

But both of these buttons don't open the other modals. If I add the buttons to open the second and third modal to the body and not to the first modal they both open.

Is there any way to get this to work?

**Comment by JohnSThomas** [comment]
That is considered bad UX. You should do something other than a modal. Maybe a curtain (slide down window), or change the contents of the modal itself. This is easy to do with jQuery.

**Comment by ismaelw** [comment]
Is this like the badest answer for a real code bug? Well, it's like a problem from a half year ago. I already used another modal for my tool. This one is good for one single modal. But for a complex page it's useless..

**Comment by JohnSThomas** [comment]
It is not a bug, it is a feature by design to prevent **horrible** user experiences. You should never have modals opening more modals. We will **NOT** add this as a feature.
